### ISSUE TITLE
good first issue

### ISSUE THREAD

**Issue by AnamuddinAhmad** [AnamuddinAhmad/Portfolio#1]
1. [ ] Here is a issue in contact form. Its not connected from email.
2. [ ] If any one fill the contact form that data i couldn't recive.
3. [ ] please solve this problem
4. [ ] if You want to solve this problem so please solve it.
5. [ ] @[https://anamuddinahmad.github.io/Portfolio/contact.html](url)

**Comment by Ashutosh-510** [comment]
Hey Anamuddin , Can you elaborate about your issue ?

**Comment by AnamuddinAhmad** [comment]
are you intrested to work on this project

**Comment by AnamuddinAhmad** [comment]
in this port-folio .
in the last there is contact form but it not working can you work on that .
if any one want to send me through that form then i recive through my email

**Comment by psonera** [comment]
Hi @AnamuddinAhmad, Can you please give me your email id, so I can add it in the form submission?

**Comment by AnamuddinAhmad** [comment]
> 

ok I can assign  you for this work |

**Comment by AnamuddinAhmad** [comment]
@psonera You can text me on linked in

**Comment by AnamuddinAhmad** [comment]
@psonera ok I will assign you for this work

**Comment by AnamuddinAhmad** [comment]
@Ashutosh-510 YOU CAN CHECK COMMENT SECTION |

**Comment by reerajput930** [comment]
is your problem solved?

**Comment by AnamuddinAhmad** [comment]
@reerajput930 NO CAN YOU SOLVE IT

**Comment by reerajput930** [comment]
> yeah , I ll be happy to help you.
also i was looking for contribution and i guess your project is a good start for me :>

**Comment by AnamuddinAhmad** [comment]
@reerajput930  I will glad to assign with you.

**Comment by AnamuddinAhmad** [comment]
Riya please make my website responsive to all pages

**Comment by reerajput930** [comment]
yeah , i am working on it!

**Comment by AnamuddinAhmad** [comment]
Awesome, thanks!

**Comment by StefanBeh** [comment]
Is this issue still open?

**Comment by NkOffiCiAL07** [comment]
@AnamuddinAhmad I hope the issue is closed now.

**Comment by AnamuddinAhmad** [comment]
@NkOffiCiAL07  If you want then you can work on it for make it responsive

**Comment by AnamuddinAhmad** [comment]
@StefanBeh Yep are you interested ?

**Comment by StefanBeh** [comment]
Yes I would love to fix this for you. 🙂

**Comment by AnamuddinAhmad** [comment]
@StefanBeh Ok if you want then you can work on it and make it responsive

**Comment by AnamuddinAhmad** [comment]
@StefanBeh And you can also change the design and send me a pull_request

**Comment by GIT-Gizmo** [comment]
Hi, has the issue been resolved?

**Comment by AnamuddinAhmad** [comment]
@GIT-Gizmo  Not Right now.
If you intrested then you can make it responsive

**Comment by GIT-Gizmo** [comment]
All I need to do is to make it responsive right?

**Comment by AnamuddinAhmad** [comment]
@GIT-Gizmo Yep You have to make it responsive. if you are interested then text me I'm interested.
