### ISSUE TITLE
Making the site responsive!

### ISSUE THREAD

**Issue by reerajput930** [AnamuddinAhmad/Portfolio#2]
**PORTFOLIO IS NOT RESPONSIVE**

- [x] I will use the display flex to make it Responsive.
- [x] code will be simple, clean, and well-commented.

**Comment by reerajput930** [comment]
you can also, assign this task to me.

**Comment by AnamuddinAhmad** [comment]
@reerajput930 Yeah you can check I have already assign you.

**Comment by AnamuddinAhmad** [comment]
@reerajput930 I know portfolio is not responsive that's why I tell you please work on it.
And one more thing i have semester exam after few day's so please help me
And also solve the contact form issue pleae

**Comment by reerajput930** [comment]
need not to worry. :>

**Comment by AnamuddinAhmad** [comment]
@reerajput930  I'm sorry about which I text you on Instagram 
I think you are not active on github like other's..

**Comment by reerajput930** [comment]
Hello, check the code and merge it. and if you want any other changes let me know!

**Comment by AnamuddinAhmad** [comment]
@reerajput930 hello

**Comment by AnamuddinAhmad** [comment]
@reerajput930  Wo code merge kr dea hu
aur aap please dusre page ke liye kaam kr sakte ho ??
jaise index page

**Comment by AnamuddinAhmad** [comment]
@reerajput930  code merge ho gya hai kya mujhe jyada experience nahi hai
